### ISSUE TITLE
Extend support for Xiaomi Yeelight

### ISSUE THREAD

**Issue by William1444** [sandeepmistry/node-yeelight-blue#5]
Hi, using this library, I have been trying to connect to my new Xiaomi Yeelight lamp.

Unfortunately I can't find the bluetooth messaging documentation for it so have been reverse engineering the interface (or trying to!)

I think the service id is fee7.. but not sure. I changed the `YeelightBlue.is` function to include the name 'XMCTD_', and have tried sending the code for red, 100% brightness to all characteristics on all service ids... but no joy :(.. 

Have you got any advice on what I should try next?? This is my first bluetooth device endeavour!

**Comment by sandeepmistry** [comment]
Hi @William1444,

The Xiaomi Yeelight shares the same name, but it's a completely different device.

I suggest you work with @Marcocanc here: https://github.com/Marcocanc/node-mi-lamp
